// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/tfplugin/tfplugin.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	graphql "github.com/threefoldtech/tfgrid-sdk-go/grid-client/graphql"
	"github.com/threefoldtech/tfgrid-sdk-go/grid-client/workloads"
	types "github.com/threefoldtech/tfgrid-sdk-go/grid-proxy/pkg/types"
	gridtypes "github.com/threefoldtech/zos/pkg/gridtypes"
)

// MockTFPluginClientInterface is a mock of TFPluginClientInterface interface.
type MockTFPluginClientInterface struct {
	ctrl     *gomock.Controller
	recorder *MockTFPluginClientInterfaceMockRecorder
}

// MockTFPluginClientInterfaceMockRecorder is the mock recorder for MockTFPluginClientInterface.
type MockTFPluginClientInterfaceMockRecorder struct {
	mock *MockTFPluginClientInterface
}

// NewMockTFPluginClientInterface creates a new mock instance.
func NewMockTFPluginClientInterface(ctrl *gomock.Controller) *MockTFPluginClientInterface {
	mock := &MockTFPluginClientInterface{ctrl: ctrl}
	mock.recorder = &MockTFPluginClientInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTFPluginClientInterface) EXPECT() *MockTFPluginClientInterfaceMockRecorder {
	return m.recorder
}

// CancelContract mocks base method.
func (m *MockTFPluginClientInterface) CancelContract(contractID uint64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CancelContract", contractID)
	ret0, _ := ret[0].(error)
	return ret0
}

// CancelContract indicates an expected call of CancelContract.
func (mr *MockTFPluginClientInterfaceMockRecorder) CancelContract(contractID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CancelContract", reflect.TypeOf((*MockTFPluginClientInterface)(nil).CancelContract), contractID)
}

// DeployDeployment mocks base method.
func (m *MockTFPluginClientInterface) DeployDeployment(ctx context.Context, dl *workloads.Deployment) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeployDeployment", ctx, dl)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeployDeployment indicates an expected call of DeployDeployment.
func (mr *MockTFPluginClientInterfaceMockRecorder) DeployDeployment(ctx, dl interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeployDeployment", reflect.TypeOf((*MockTFPluginClientInterface)(nil).DeployDeployment), ctx, dl)
}

// DeployGatewayName mocks base method.
func (m *MockTFPluginClientInterface) DeployGatewayName(ctx context.Context, gw *workloads.GatewayNameProxy) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeployGatewayName", ctx, gw)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeployGatewayName indicates an expected call of DeployGatewayName.
func (mr *MockTFPluginClientInterfaceMockRecorder) DeployGatewayName(ctx, gw interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeployGatewayName", reflect.TypeOf((*MockTFPluginClientInterface)(nil).DeployGatewayName), ctx, gw)
}

// DeployNetwork mocks base method.
func (m *MockTFPluginClientInterface) DeployNetwork(ctx context.Context, znet *workloads.ZNet) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeployNetwork", ctx, znet)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeployNetwork indicates an expected call of DeployNetwork.
func (mr *MockTFPluginClientInterfaceMockRecorder) DeployNetwork(ctx, znet interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeployNetwork", reflect.TypeOf((*MockTFPluginClientInterface)(nil).DeployNetwork), ctx, znet)
}

// FilterNodes mocks base method.
func (m *MockTFPluginClientInterface) FilterNodes(filter types.NodeFilter, pagination types.Limit) ([]types.Node, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FilterNodes", filter, pagination)
	ret0, _ := ret[0].([]types.Node)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// FilterNodes indicates an expected call of FilterNodes.
func (mr *MockTFPluginClientInterfaceMockRecorder) FilterNodes(filter, pagination interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FilterNodes", reflect.TypeOf((*MockTFPluginClientInterface)(nil).FilterNodes), filter, pagination)
}

// GetDeployment mocks base method.
func (m *MockTFPluginClientInterface) GetDeployment(nodeID uint32, contractID uint64) (gridtypes.Deployment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDeployment", nodeID, contractID)
	ret0, _ := ret[0].(gridtypes.Deployment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDeployment indicates an expected call of GetDeployment.
func (mr *MockTFPluginClientInterfaceMockRecorder) GetDeployment(nodeID, contractID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDeployment", reflect.TypeOf((*MockTFPluginClientInterface)(nil).GetDeployment), nodeID, contractID)
}

// GetGridNetwork mocks base method.
func (m *MockTFPluginClientInterface) GetGridNetwork() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetGridNetwork")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetGridNetwork indicates an expected call of GetGridNetwork.
func (mr *MockTFPluginClientInterfaceMockRecorder) GetGridNetwork() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetGridNetwork", reflect.TypeOf((*MockTFPluginClientInterface)(nil).GetGridNetwork))
}

// ListContractsOfProjectName mocks base method.
func (m *MockTFPluginClientInterface) ListContractsOfProjectName(projectName string) (graphql.Contracts, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListContractsOfProjectName", projectName)
	ret0, _ := ret[0].(graphql.Contracts)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListContractsOfProjectName indicates an expected call of ListContractsOfProjectName.
func (mr *MockTFPluginClientInterfaceMockRecorder) ListContractsOfProjectName(projectName interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListContractsOfProjectName", reflect.TypeOf((*MockTFPluginClientInterface)(nil).ListContractsOfProjectName), projectName)
}

// LoadGatewayNameFromGrid mocks base method.
func (m *MockTFPluginClientInterface) LoadGatewayNameFromGrid(nodeID uint32, name, deploymentName string) (workloads.GatewayNameProxy, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LoadGatewayNameFromGrid", nodeID, name, deploymentName)
	ret0, _ := ret[0].(workloads.GatewayNameProxy)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LoadGatewayNameFromGrid indicates an expected call of LoadGatewayNameFromGrid.
func (mr *MockTFPluginClientInterfaceMockRecorder) LoadGatewayNameFromGrid(nodeID, name, deploymentName interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LoadGatewayNameFromGrid", reflect.TypeOf((*MockTFPluginClientInterface)(nil).LoadGatewayNameFromGrid), nodeID, name, deploymentName)
}

// LoadVMFromGrid mocks base method.
func (m *MockTFPluginClientInterface) LoadVMFromGrid(nodeID uint32, name, deploymentName string) (workloads.VM, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LoadVMFromGrid", nodeID, name, deploymentName)
	ret0, _ := ret[0].(workloads.VM)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LoadVMFromGrid indicates an expected call of LoadVMFromGrid.
func (mr *MockTFPluginClientInterfaceMockRecorder) LoadVMFromGrid(nodeID, name, deploymentName interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LoadVMFromGrid", reflect.TypeOf((*MockTFPluginClientInterface)(nil).LoadVMFromGrid), nodeID, name, deploymentName)
}
