// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Execute(arg1) {
  return window['go']['main']['App']['Execute'](arg1);
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function Logout() {
  return window['go']['main']['App']['Logout']();
}

export function OnAnalyzing() {
  return window['go']['main']['App']['OnAnalyzing']();
}

export function OnAnswer(arg1) {
  return window['go']['main']['App']['OnAnswer'](arg1);
}

export function OnCommand(arg1, arg2) {
  return window['go']['main']['App']['OnCommand'](arg1, arg2);
}

export function OnError(arg1) {
  return window['go']['main']['App']['OnError'](arg1);
}

export function OnFetchURL(arg1, arg2) {
  return window['go']['main']['App']['OnFetchURL'](arg1, arg2);
}

export function OnProcessing() {
  return window['go']['main']['App']['OnProcessing']();
}

export function OnQuestion(arg1) {
  return window['go']['main']['App']['OnQuestion'](arg1);
}

export function SaveSettings(arg1, arg2, arg3) {
  return window['go']['main']['App']['SaveSettings'](arg1, arg2, arg3);
}

export function SendMessage(arg1) {
  return window['go']['main']['App']['SendMessage'](arg1);
}

export function SetTheme(arg1) {
  return window['go']['main']['App']['SetTheme'](arg1);
}
