// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function Execute(arg1:Array<string>):Promise<string>;

export function GetSettings():Promise<main.Settings>;

export function Logout():Promise<void>;

export function OnAnalyzing():Promise<void>;

export function OnAnswer(arg1:string):Promise<void>;

export function OnCommand(arg1:string,arg2:string):Promise<void>;

export function OnError(arg1:string):Promise<void>;

export function OnFetchURL(arg1:string,arg2:string):Promise<void>;

export function OnProcessing():Promise<void>;

export function OnQuestion(arg1:string):Promise<void>;

export function SaveSettings(arg1:string,arg2:string,arg3:string):Promise<void>;

export function SendMessage(arg1:string):Promise<main.Message>;

export function SetTheme(arg1:string):Promise<void>;
