-- ============================================================================
-- CACHE SETUP SCRIPT - REFERENCE
-- ============================================================================
-- This file is kept for reference. The actual setup is now split into
-- organized module files in the setup/ directory and combined at runtime
-- by the Go application.
--
-- Module Structure:
--   1. setup/01_functions.sql - Helper functions (calc_price, calc_discount, etc.)
--   2. setup/02_views.sql - Base views (resources_cache_view)
--   3. setup/03_cache_tables.sql - Cache table definitions (resources_cache, public_ips_cache)
--   4. setup/04_indexes.sql - Performance indexes
--   5. setup/05_triggers.sql - Trigger functions and triggers
--   6. setup/06_cache_management.sql - Cache refresh and validation functions
--
-- The Go code in postgres.go embeds all these files and combines them
-- into a single transaction (BEGIN...COMMIT) at runtime.
--
-- ============================================================================
