name: Grid3 Go Testing

on:
  push:
    paths:
      - grid-client/**
      - rmb-sdk-go/**
      - grid-proxy/**
  workflow_dispatch:

defaults:
  run:
    working-directory: grid-client

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21"
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v4
        with:
          submodules: "true"

      - name: Get dependencies
        run: |
          go mod download

      - name: Test
        env:
          MNEMONICS: ${{ secrets.MNEMONICS }}
          NETWORK: dev
        run: go test -v `go list ./... | grep -v integration_tests`
