name: gridify lint

defaults:
  run:
    working-directory: gridify

on:
  push:
    paths:
      - gridify/**
  workflow_dispatch:

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21"
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v4
        with:
          submodules: "true"

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          args: --timeout 3m --verbose
          working-directory: gridify

      - name: gofmt
        uses: Jerome1337/gofmt-action@v1.0.5
        with:
          gofmt-flags: "-l -d"
